In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\dell\anaconda3\lib\site-packages (4.8.0)
Requirement already satisfied: trio~=0.17 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sniffio in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sortedcontainers in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: idna in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dell\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [9]:
import selenium
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import requests
import time

In [10]:
driver=webdriver.Chrome(r"C:\Users\Dell\Desktop\fliprobonotes\chromedriver.exe")

In [11]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)
time.sleep(6)
driver.maximize_window()

In [12]:
# creating empty lists for scraping data
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [13]:
# Scraping Book_name
book_name=driver.find_elements('xpath',"//table[@class='in-article sortable']/tbody/tr/td[2]")
for i in book_name:
    if i.text is None:
        Book_name.append('--')
    else:
        Book_name.append(i.text)

In [14]:
# Scraping Author_name
author_name=driver.find_elements('xpath',"//table[@class='in-article sortable']/tbody/tr/td[3]")
for i in author_name:
    if i.text is None:
        Author_name.append('--')
    else:
        Author_name.append(i.text)

In [16]:
# Scraping Volumes_sold
volumes_sold=driver.find_elements('xpath',"//table[@class='in-article sortable']/tbody/tr/td[4]")
for i in volumes_sold:
    if i.text is None:
        Volumes_sold.append('--')
    else:
        Volumes_sold.append(i.text)
        
# Scraping Author_name
publisher=driver.find_elements('xpath',"//table[@class='in-article sortable']/tbody/tr/td[5]")
for i in publisher:
    if i.text is None:
        Publisher.append('--')
    else:
        Publisher.append(i.text)
        
# Scraping Genre
genre=driver.find_elements('xpath',"//table[@class='in-article sortable']/tbody/tr/td[6]")
for i in genre:
    if i.text is None:
        Genre.append('--')
    else:
        Genre.append(i.text)

In [17]:
Top_selling_book=pd.DataFrame({})
Top_selling_book['Book_name']=Book_name
Top_selling_book['Author_name']=Author_name
Top_selling_book['Volumes_sold']=Volumes_sold
Top_selling_book['Publisher']=Publisher
Top_selling_book['Genre']=Genre
Top_selling_book

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General